{"Launchpad":"https://bugs.launchpad.net/bugs/1446031","Id":"1446031","Gerrit":"https://review.openstack.org/238147","IdGerrit":"238147","IdCommit":"8a594c837c0ffeba2b6b93b79bf079d3a8129d46","Files":["cinder/scheduler/filter_scheduler.py","cinder/tests/unit/scheduler/test_filter_scheduler.py"],"Lines_Inseted":4,"Lines_Deleted":0,"CommitParent":"7fb767f2d652f070a20fd70d92585d61e56f3a50","Classification":"Bug","KeywordsTitle":"AttributeError, has no attribute","Description":"AttributeError: 'NoneType' object has no attribute 'get' ","KeywordsCommit":"Fix NoneType Attribute error Currently, fails","Comments":""}