{"Launchpad":"https://bugs.launchpad.net/bugs/1505572","Id":"1505572","Gerrit":"https://review.openstack.org/240448","IdGerrit":"240448","IdCommit":"e84222ea2bb7c04bddafc8470cb3441388722aaa","Files":["cinder/db/sqlalchemy/api.py","cinder/tests/unit/db/test_finish_migration.py"],"Lines_Inseted":28,"Lines_Deleted":8,"CommitParent":"810365f320eee5358ec0d3a147eb1fa1d3dd2af2","Classification":"Not_Bug","KeywordsTitle":"fails","Description":"error, failed","KeywordsCommit":"load additional models","Comments":""}